#!/bin/bash

for ((i = 1; i <= $#; i++));
do
    case ${!i} in
        -h|--help)
            echo "Build docker images for all homeworks or only for target
            --help                       print this info
            -t | --target [homework dir] build images only for target homework"   
            exit 0
            ;;
        -t|--target)
            target=$((i+1))
            build_file="./homework/${!target}/docker-compose.yml"
            if [[ ! -z ${!target} ]] && [[ -d ./homework/${!target} ]] && [[ -f $build_file ]];
            then
                docker compose -f $build_file up --pull never --build
                exit $?
            else
                echo "Argument for target is invalid on not provided"
                exit 1
            fi
            ;;
    esac

    echo "Unknown argument: ${!i}"
    exit 1

done

for i in `ls -d ./homework/*/`
do
    build_file="`realpath ${i}`/docker-compose.yml"
    if [[ -f $build_file ]];
    then
        docker compose -f $build_file up --pull never --build
        if [[ $? -ne 0 ]];
        then
            echo "error when build docker image for $i"
            exit $?
        fi
    fi
done
exit 0
